version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
  - name: v3.4.0-last
    branch: v3.4.0-last
    mode: pull-request
apps:
  - name: AppCash
    path: tests/server/
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
  - name: jeecgboot-vue3
    path: app/new/
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
